# Generated by Django 6.0.2 on 2026-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_custom',
            field=models.ImageField(blank=True, help_text='Thumbnail personalizado (para videos no YouTube)', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='tipo',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('url_directa', 'URL Directa (MP4/M3U8)'), ('iframe', 'iFrame Personalizado')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video',
            field=models.URLField(help_text='Link del video (YouTube, MP4, o URL del streaming)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Se extrae automáticamente si es YouTube', max_length=20),
        ),
    ]
