# Generated by Django 6.0.2 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(help_text='ID del fixture en API-Football', unique=True)),
                ('liga_nombre', models.CharField(max_length=100)),
                ('liga_logo', models.URLField(blank=True)),
                ('liga_api_id', models.PositiveIntegerField(default=0)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_local_logo', models.URLField(blank=True)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('equipo_visitante_logo', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('NS', 'No iniciado'), ('1H', 'Primer tiempo'), ('HT', 'Entretiempo'), ('2H', 'Segundo tiempo'), ('FT', 'Finalizado'), ('AET', 'Tiempo extra'), ('PEN', 'Penales'), ('SUSP', 'Suspendido'), ('PST', 'Pospuesto'), ('CANC', 'Cancelado'), ('LIVE', 'En vivo')], default='NS', max_length=10)),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='MapeoLigaCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga_api_id', models.PositiveIntegerField(help_text='ID de la liga en API-Football', unique=True)),
                ('liga_nombre', models.CharField(help_text='Nombre de la liga (ej: La Liga, Premier League)', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('canales', models.ManyToManyField(blank=True, help_text='Videos/canales que transmiten esta liga', to='canales.video')),
            ],
            options={
                'verbose_name': 'Mapeo Liga-Canal',
                'verbose_name_plural': 'Mapeos Liga-Canal',
                'ordering': ['liga_nombre'],
            },
        ),
    ]
