# Generated by Django 6.0.2 on 2026-03-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0002_partido_mapeoligacanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='canales_bolaloca',
            field=models.CharField(blank=True, help_text='Canales bolaloca (ej: 81,87,94)', max_length=200),
        ),
    ]
