# Generated by Django 6.0.2 on 2026-03-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0003_partido_canales_bolaloca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='canales_bolaloca',
            field=models.CharField(blank=True, help_text='Números de canales bolaloca separados por coma (ej: 81,87,94)', max_length=200),
        ),
    ]
