# Generated by Django 5.1.6 on 2026-04-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0005_partido_minuto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='redes/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red / Marca',
                'verbose_name_plural': 'Redes / Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='ligas',
            field=models.ManyToManyField(blank=True, related_name='canales', to='canales.liga', verbose_name='Competiciones que transmite'),
        ),
        migrations.AddField(
            model_name='canal',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canales', to='canales.redcanal', verbose_name='Red / Marca'),
        ),
    ]
