# Generated by Django 6.0.2 on 2026-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0005_remove_video_liga_video_ligas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalBolaloca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numero del canal (CH1, CH2...)', unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, help_text='es, fr, de, uk, it, etc.', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bolaloca - Canal',
                'verbose_name_plural': 'Bolaloca - Canales',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EventoBolaloca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('liga', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('canales', models.ManyToManyField(blank=True, to='canales.canalbolaloca')),
            ],
            options={
                'verbose_name': 'Bolaloca - Evento',
                'verbose_name_plural': 'Bolaloca - Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
