# Generated by Django 5.1.6 on 2026-04-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0006_redcanal_canal_ligas_canal_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='canales',
            field=models.ManyToManyField(blank=True, related_name='partidos', to='canales.canal', verbose_name='Canales que transmiten'),
        ),
    ]
