# Generated by Django 6.0.2 on 2026-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0006_canalbolaloca_eventobolaloca'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='bolaloca_canales',
            field=models.ManyToManyField(blank=True, help_text='Canales de bolaloca asociados a este canal', to='canales.canalbolaloca'),
        ),
    ]
