# Generated by Django 6.0.2 on 2026-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0007_canal_bolaloca_canales'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bolaloca_canales',
            field=models.ManyToManyField(blank=True, help_text='Canales de bolaloca asociados a este canal', to='canales.canalbolaloca'),
        ),
    ]
