# Generated by Django 6.0.2 on 2026-02-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0008_video_bolaloca_canales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='bolaloca_canales',
        ),
        migrations.RemoveField(
            model_name='video',
            name='bolaloca_canales',
        ),
        migrations.AddField(
            model_name='canal',
            name='bolaloca_canal',
            field=models.ForeignKey(blank=True, help_text='Canal de bolaloca asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='canales.canalbolaloca'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_custom',
            field=models.FileField(blank=True, help_text='Thumbnail personalizado', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Se extrae automaticamente si es YouTube', max_length=20),
        ),
    ]
