# Generated by Django 6.0.2 on 2026-02-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0009_remove_canal_bolaloca_canales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='bolaloca_canal',
        ),
        migrations.AddField(
            model_name='video',
            name='bolaloca_canal',
            field=models.ForeignKey(blank=True, help_text='Canal de bolaloca asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='canales.canalbolaloca'),
        ),
    ]
