# Generated by Django 6.0.2 on 2026-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0010_remove_canal_bolaloca_canal_video_bolaloca_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stream_id',
            field=models.CharField(blank=True, help_text='ID del stream en streamx10 (ej: espn, espn2, winplus)', max_length=50),
        ),
    ]
