# Generated by Django 6.0.2 on 2026-02-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0011_video_stream_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('dominio', models.CharField(help_text='Ej: streamx10.cloud, bolaloca.my', max_length=200)),
                ('ruta', models.CharField(blank=True, help_text='Ej: global1.php?channel=, player/1/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion Streaming',
                'verbose_name_plural': 'Configuracion Streaming',
            },
        ),
    ]
