# Generated by Django 6.0.2 on 2026-02-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0012_configstreaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tvtvhd_id',
            field=models.CharField(blank=True, help_text='ID en tvtvhd (ej: espn, winsportsplus)', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='stream_id',
            field=models.CharField(blank=True, help_text='ID en streamx (ej: espn, espn2, winplus)', max_length=50),
        ),
    ]
