# Generated by Django 6.0.2 on 2026-03-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0014_alter_canal_logo_alter_canal_url_sitio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='canales/'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ligas/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_custom',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
