# Generated by Django 6.0.2 on 2026-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0016_bannerimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimagen',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion corta del banner'),
        ),
    ]
